# This is a basic workflow to help you get started with Actions

name: Latest blog post workflow 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule: # Run workflow automatically
    - cron: '0 23 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path: ./content.md
          comment_tag_name: AZUREWEEKLY
          feed_list: "https://azureweekly.info/rss.xml"
        
      - uses: khaosdoctor/blog-post-workflow@master
        with:
          comment_tag_name: DEVBLOGDEVOPS
          feed_list: "https://devblogs.microsoft.com/devops/feed/"
          custom_tags: "desc/description/"
          template: $newline - [$title]($url) ($date)
          date_format: mm/dd/yy
          tag_post_pre_newline: true
          committer_username: blog-post-bot
          committer_email: blog-post-bot@example.com
          
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: AZUREINFOHUB
          feed_list: "https://azureinfohub.azurewebsites.net/feed?serviceTitle=GitHub%20Actions,https://azureinfohub.azurewebsites.net/feed?serviceTitle=GitHub,https://azureinfohub.azurewebsites.net/feed?serviceTitle=Azure%20DevOps"

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: AZUREUPDATES 
          feed_list: "https://azurecomcdn.azureedge.net/en-us/blog/topics/devops/feed/"
          custom_tags: "desc/description/"
          template: $newline - [$title]($url) ($date)
          date_format: mm/dd/yy
          tag_post_pre_newline: true
          committer_username: blog-post-bot
          committer_email: blog-post-bot@example.com

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: MSOPENSOURCEBLOG
          feed_list: "https://cloudblogs.microsoft.com/opensource/feed/?product=devops"
          custom_tags: "desc/description/"
          template: $newline - [$title]($url) ($date)
          date_format: mm/dd/yy
          tag_post_pre_newline: true
          committer_username: blog-post-bot
          committer_email: blog-post-bot@example.com

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: GITHUB
          feed_list: "https://github.blog/feed/"
          custom_tags: "desc/description/"
          template: $newline - [$title]($url) ($date)
          date_format: mm/dd/yy
          tag_post_pre_newline: true
          committer_username: blog-post-bot
          committer_email: blog-post-bot@example.com          

