name: Create newsletter file for GH pages

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      comment:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Add a small comment'
        # Default value if no value is explicitly provided
        default: 'This is the nicest newsletter'
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  create_post:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          token: '${{secrets.GITHUB_TOKEN}}'

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Merge cartridge with content to create post
        run: |
          awk 'FNR==1{print ""}{print}' ./cartridge.yml ./content.yml > ./post.yml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Publish post for month xxx
          body: Few change for this, LGTM ;-)
          branch: autopublish-${{ steps.date.outputs.date }}

      

