name: Create newsletter

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  create_post:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          token: '${{secrets.GITHUB_TOKEN}}'

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Set the newsletter filename
        id: step_one
        run: |
          echo "last_newsletter=post-${{ steps.date.outputs.date }}.yml" >> $GITHUB_ENV

      - name: Merge cartridge with content to create newsletter
        run: |
          awk 'FNR==1{print ""}{print}' ./cartridge.yml ./content.yml > ./post-${{ steps.date.outputs.date }}.yml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Publish post for current month
          body: Few change for this, LGTM ;-)
          branch: autopublish-${{ steps.date.outputs.date }}
          base: ${{ github.head_ref }}
          labels: 'publish_newsletter'

      

