name: Create newsletter

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  create_post:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%B-%Y')"

      - name: Merge cartridge with content to create newsletter
        run: |
          awk 'FNR==1{print ""}{print}' ./cartridge.md ./content.md > ./post.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Publishing for ${{ steps.date.outputs.date }} newsletter'
          body: Nothing to comment
          branch: autopublish-${{ steps.date.outputs.date }}
          labels: 'publish_newsletter'

      

