name: Publish newsletter to GH Pages 
on: 
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  publish_newsletter_on_blog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref,'autopublish-')
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main      

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: toomone/fake-blog
          path: blog

      - name: Get current full date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get current month and year
        id: month
        run: echo "::set-output name=month::$(date +'%B-%Y')"      

      - name: Target filename
        id: targetfilename
        run: echo "::set-output name=targetfilename::${{ steps.date.outputs.date }}-newsletter-${{ steps.month.outputs.month }}.md" 

      - name: Rename post file
        working-directory: ./main
        run: git mv post.md ${{ steps.targetfilename.outputs.targetfilename }}

      - name: Commit renamed post file
        working-directory: ./main
        run: git commit . -m "Renamed post file"

      - name: Copy file to blog
        working-directory: ./main
        run: cp ${{ steps.targetfilename.outputs.targetfilename }} ../blog/_posts/     

      - uses: actions/checkout@v2
        working-directory: ./blog
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Renamed post file"
          git push            
