name: Publish newsletter
on: 
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  publish_newsletter:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref,'autopublish-')
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%MMMM')"

      - name: Rename post file
        run: git mv post.yml post-${{ steps.date.outputs.date }}.yml

      - name: Push newsletter file
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'post-${{ steps.date.outputs.date }}.yml'
          destination_repo: 'toomone/fake-blog'
          destination_folder: '_posts'
          user_email: 'thomas.cousin@gmail.com'
          user_name: 'toomone'
          commit_message: 'Devops newsletter on ${{ steps.date.outputs.date }}'