name: Publish newsletter
on: 
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  publish_newsletter:
    runs-on: ubuntu-latest
    if: startsWith(github.ref,'refs/heads/autopublish-') || startsWith(github.event.pull_request.base.ref,'refs/heads/autopublish-')
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"